spotify:
    clientID: 8331ef509219468482182ec02c7fce76
    clientSecret: a4a2254525d94d6bb140e2e7db52c778
    redirectURI: http://localhost
    scope: user-library-modify,user-library-read,user-read-currently-playing,user-read-playback-position,user-read-playback-state,user-modify-playback-state,app-remote-control,streaming,playlist-read-private,playlist-modify-private,playlist-modify-public
    cache: .spotipyoauthcache